name: ci

on:
  push:
    paths-ignore:
      - 'guides/**'

permissions: read-all

jobs:
  ci:
    env:
      MIX_ENV: test
      DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              elixir: '1.19.5-otp-28'
              otp: '28.4.1'

    runs-on: ubuntu-24.04

    services:
      # Label used to access the service container
      hex_beefy:
        # Docker Hub image
        image: camatcode/hex_beefy:with_test_user
        ports:
          - 4000:4000

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: erlef/setup-beam@ee09b1e59bb240681c382eb1f0abc6a04af72764 # v1.23.0
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}

      - uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{matrix.pair.elixir}}-${{matrix.pair.otp}}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{matrix.pair.elixir}}-${{matrix.pair.otp}}-

      - name: Run mix deps.get
        run: mix deps.get --only test

      - name: Run mix format
        run: mix format --check-formatted

#      - name: Run mix deps.unlock
#        run: mix deps.unlock --check-unused

      - name: Run mix deps.compile
        run: mix deps.compile

      - name: Run mix compile
        run: mix compile --warnings-as-errors

      - name: Run credo
        run: mix credo --strict

      - name: Run tests
        run: mix coveralls.github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run dialyzer
        run: mix dialyzer
